// GENERATED by scripts/stamp-engine-version.mjs — DO NOT EDIT BY HAND.
// The hash of the engine files (see scripts/_lib/engineVersion.mjs ENGINE_FILES). A saved cart line
// carries the value that built it; CRM's Approve compares it to this one and warns when the engine
// has changed since the save (Shared/cartStaleness). Regenerated by "npm run build" (prebuild); the
// harness (scripts/cartStaleness.test.mjs) fails when the committed stamp is behind the code.
export const ENGINE_VERSION = 'e8b04d5b079a';
