// THE ENGINE'S VERSION IS ITS SOURCE (S1, Stuart 2026-09-15). Four quotes saved on 09-10 were
// approved on 09-14 carrying the BOM the engine built BEFORE that evening's rider fixes — the
// standoffs a wood-pole order never needed reached the pick and NetSuite. A saved line now carries
// the hash of the engine files that built it (Shared/engineVersion.js, generated from these files
// by scripts/stamp-engine-version.mjs on every build), and Approve compares. Nothing to remember
// to bump: the version IS the code.
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** The files whose change means "a saved line may no longer be what the engine builds". */
export const ENGINE_FILES = [
    'src/components/Shared/hardwareModel.js',      // the resolver: slots, riders, companions, the BOM
    'src/components/Shared/hardwareAdapter.js',    // pins → choices (every tag the resolver reads)
    'src/components/Shared/hardwareHandoff.js',    // resolved model → the saved line and its rows
    'src/components/Shared/hardwarePricing.js',    // the money on those rows
    'src/components/Shared/kitSeed.js',            // the kit bill shape
];

export const STAMP_FILE = 'src/components/Shared/engineVersion.js';

export function computeEngineVersion(root = ROOT) {
    const h = createHash('sha1');
    for (const f of ENGINE_FILES) { h.update(f); h.update('\0'); h.update(readFileSync(join(root, f))); h.update('\0'); }
    return h.digest('hex').slice(0, 12);
}

export function stampSource(version) {
    return `// GENERATED by scripts/stamp-engine-version.mjs — DO NOT EDIT BY HAND.\n`
        + `// The hash of the engine files (see scripts/_lib/engineVersion.mjs ENGINE_FILES). A saved cart line\n`
        + `// carries the value that built it; CRM's Approve compares it to this one and warns when the engine\n`
        + `// has changed since the save (Shared/cartStaleness). Regenerated by "npm run build" (prebuild); the\n`
        + `// harness (scripts/cartStaleness.test.mjs) fails when the committed stamp is behind the code.\n`
        + `export const ENGINE_VERSION = '${version}';\n`;
}

/** The version the committed stamp file declares ('' when the file is missing or unreadable). */
export function committedEngineVersion(root = ROOT) {
    try { const m = readFileSync(join(root, STAMP_FILE), 'utf8').match(/ENGINE_VERSION = '([0-9a-f]+)'/); return m ? m[1] : ''; }
    catch { return ''; }
}
